name : Continuous integration and deploiement

on:
  push:
    branches:
    - main

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      uses: actions/checkout@v3.5.2

      - name: setup-dotnet
      uses: xt0rted/setup-dotnet@v1.5.0
      with: 
        dotnet-version : "5.0.X"

      -name: Restore dependencies
      run : dotnet restore

      name: Build app
      run: dotnet build -c Release --no-restore 

