name: Continuous integration and deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: setup-dotnet
        uses: xt0rted/setup-dotnet@v1.5.0
        with:
          dotnet-version: "6.0.x"

      - name: Restore dependencies
        run: dotnet restore 

      - name: Build App
        run:  |
          cd mercadona-api
          dotnet build -c Release --no-restore

      - name: publish App
        run:  |
          cd mercadona-api
          dotnet publish -c Release -o ./out 

      - name: Deploy to Azure WebApp
        uses: Azure/webapps-deploy@v2
        with: 
          app-name: 'mercadona-zaina'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_2479CBB6F70C434F93FA538B0A87F694 }}



        
