name: Continuous integration and deployment

on:
  push:
    branches:
      - main
      
env:
  AZURE_WEBAPP_NAME: Mercadona-api
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: setup-dotnet
        uses: xt0rted/setup-dotnet@v1.5.0
        with:
          dotnet-version: "6.0.x"

      - name: Restore dependencies
        run: |
          
          cd api
          ls
          dotnet restore 

      - name: Build App
        run:  |
          
          cd api
          dotnet build ./api.sln -c Release --no-restore 

      - name: publish App
        run:  |
          
          cd api
          dotnet publish ./api.sln -c Release --no-build --output '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
          
      - name: Show current working directory
        run: |
          cd api
          pwd
          ls
          
      - name: Deploy to Azure WebApp
        uses: Azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_2479CBB6F70C434F93FA538B0A87F694 }}
          package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"



        
