name: Deploy to mercadona angular to Azure

on:
  push:
    branches:
      - main
  
jobs:
    build:
      runs-on: ubuntu-latest
  
      steps:
        - uses: actions/checkout@v2
  
        - name: Set up Node.js version
          uses: actions/setup-node@v2.4.0
          with:
            node-version: '16.x'
  
        - name: npm install and build
          run: |
            cd front-end
            npm install
            npm run build --if-present
  
        - name: Run unit tests
          run: |
            cd front-end
            sed -i -z "s/ removeAllListeners()\n/ removeAllListeners();process.nextTick(() => process.exit(code || 0));\n/g" node_modules/karma/lib/server.js
            npm run test --if-present --verbose
          env:
            CI: true
          
        - name: Show test results
          run: |
            cat front-end/test-report.xml

        - name: Upload artifact for deployment job
          uses: actions/upload-artifact@v2
          with:
            name: node-app
            path: front-end/dist/front-end/
  
    deploy:
      runs-on: ubuntu-latest
      needs: build
      environment:
        name: 'Production'
        url: mercadona-angular.azurewebsites.net
  
      steps:
        - name: 'Download artifact from build job'            
          uses: actions/download-artifact@v2
          with:
            name: node-app
        
        - name: Show current working directory
          run: |
            pwd
            ls
  
        - name: 'Deploy to Azure Web App'
          id: deploy-to-webapp
          uses: azure/webapps-deploy@v2
          with:
            app-name: 'mercadona-angular'
            slot-name: 'Production'
            publish-profile:  ${{ secrets.PUBLISH_PROFILE_ANGULAR }}
            package: ./
  
