name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Navigate to front-end directory
      run: cd front-end

    - name: Setup Node.js
      uses: actions/setup-node@v2.4.0
      with:
        node-version: '14.x'

    - name: Install dependencies
      run: |
        cd front-end
        npm install

    - name: Build
      run: |
        cd front-end
        npm run build -- --prod

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: mercadona-angular
        publish-profile: ${{ secrets.PUBLISH_PROFILE_ANGULAR }}
        package: ./dist/front-end
