name: CI/CD de l'api .net6

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: setup-dotnet
        uses: xt0rted/setup-dotnet@v1.5.0
        with:
          dotnet-version: "6.0.x"
      
      - name: Replace values in appsettings.json
        run: |
          cd api
          cd api
          ls
          sed -i "s|REPLACE_DATABASE_CONNECTION_STRING|${{ secrets.DB_CONNECTION_STRING }}|g" ./appsettings.json
          sed -i "s|REPLACE_AZURE_BLOB_STORAGE_CONNECTION_STRING|${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}|g" ./appsettings.json

      - name: Show current working directory
        run: |
          pwd
          ls

      - name: Restore dependencies
        run: |
          cd api
          dotnet restore 

      - name: Build App
        run:  |
          cd api
          dotnet build -c Release --no-restore
      
    
      - name: publish App
        run:   |
            cd api
            dotnet publish -c Release -o ./out 
  
  

      - name: Deploy to Azure WebApp
        uses: Azure/webapps-deploy@v2
        with: 
          app-name: 'mercadona-api'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_2479CBB6F70C434F93FA538B0A87F694 }}
          package : ./api/out



        
