name: Continuous integration and deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: setup-dotnet
        uses: xt0rted/setup-dotnet@v1.5.0
        with:
          dotnet-version: "6.0.x"

      - name: Restore dependencies
        run: dotnet restore Backend/Backend.csproj

      - name: Build App
        run: dotnet build -c Release --no-restore
